"""empty message

Revision ID: 0ee46f22576a
Revises: 7e9a547e1d20
Create Date: 2022-11-19 00:50:31.021456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ee46f22576a'
down_revision = '7e9a547e1d20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('group',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.String(length=16),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('group',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=1),
               existing_nullable=True)

    # ### end Alembic commands ###
