"""empty message

Revision ID: 11dc07b7073f
Revises: b4d123e92b49
Create Date: 2022-12-03 23:56:41.483963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11dc07b7073f'
down_revision = 'b4d123e92b49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goleador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('standard_name', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goleador', schema=None) as batch_op:
        batch_op.drop_column('standard_name')

    # ### end Alembic commands ###
