"""empty message

Revision ID: 133630b69e63
Revises: e1c61253e2d1
Create Date: 2022-11-14 19:43:02.655058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '133630b69e63'
down_revision = 'e1c61253e2d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points_outcome', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('points_score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediction', schema=None) as batch_op:
        batch_op.drop_column('points_score')
        batch_op.drop_column('points_outcome')

    # ### end Alembic commands ###
