"""empty message

Revision ID: 5af781fab3f0
Revises: a1e91c6ff819
Create Date: 2022-11-19 00:40:59.037639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5af781fab3f0'
down_revision = 'a1e91c6ff819'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_index('ix_game_local_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.create_index('ix_game_local_time', ['local_time'], unique=False)

    # ### end Alembic commands ###
