"""empty message

Revision ID: 828faea5a6ab
Revises: 7042493e4f8a
Create Date: 2022-12-02 12:43:20.912339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '828faea5a6ab'
down_revision = '7042493e4f8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('official_winner', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('official_runnerup', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('official_runnerup')
        batch_op.drop_column('official_winner')

    # ### end Alembic commands ###
