"""empty message

Revision ID: 86ac53d37493
Revises: 3ddb632eabd5
Create Date: 2022-11-28 18:17:39.178576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86ac53d37493'
down_revision = '3ddb632eabd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_tracker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_event_tracker_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_tracker', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_tracker_timestamp'))
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
