"""empty message

Revision ID: 8ba7a9f355a3
Revises: 0ee46f22576a
Create Date: 2022-11-19 02:12:00.002020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ba7a9f355a3'
down_revision = '0ee46f22576a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('points',
    sa.Column('point_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('point_id')
    )
    with op.batch_alter_table('goleador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goleador_points', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goleador', schema=None) as batch_op:
        batch_op.drop_column('goleador_points')

    op.drop_table('points')
    # ### end Alembic commands ###
