"""empty message

Revision ID: 929fbab9dd8d
Revises: 8ba7a9f355a3
Create Date: 2022-11-19 10:37:17.776621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '929fbab9dd8d'
down_revision = '8ba7a9f355a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('points', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_description', sa.String(length=1024), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('points', schema=None) as batch_op:
        batch_op.drop_column('event_description')

    # ### end Alembic commands ###
