"""empty message

Revision ID: 99a6abcbdcfe
Revises: 346e2c64cc09
Create Date: 2022-11-29 07:26:36.905835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99a6abcbdcfe'
down_revision = '346e2c64cc09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('official_stage',
    sa.Column('stage_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tournament', sa.String(length=64), nullable=True),
    sa.Column('stage_type', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('winner', sa.String(length=32), nullable=True),
    sa.Column('runner_up', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('stage_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('official_stage')
    # ### end Alembic commands ###
