"""empty message

Revision ID: b561a7e4ff46
Revises: 5769b346d392
Create Date: 2022-11-29 12:09:21.123364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b561a7e4ff46'
down_revision = '5769b346d392'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('points', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prediction_points', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('stage_points', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('goleador_points', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('points', schema=None) as batch_op:
        batch_op.drop_column('goleador_points')
        batch_op.drop_column('stage_points')
        batch_op.drop_column('prediction_points')

    # ### end Alembic commands ###
