"""empty message

Revision ID: e1c61253e2d1
Revises: 
Create Date: 2022-11-14 18:19:11.788110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1c61253e2d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('utc_time', sa.DateTime(), nullable=True),
    sa.Column('team1', sa.String(length=3), nullable=True),
    sa.Column('team2', sa.String(length=3), nullable=True),
    sa.Column('group', sa.String(length=1), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('stage', sa.String(length=16), nullable=True),
    sa.Column('cell1', sa.String(length=4), nullable=True),
    sa.Column('cell2', sa.String(length=4), nullable=True),
    sa.PrimaryKeyConstraint('game_id')
    )
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_utc_time'), ['utc_time'], unique=False)

    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('goleador',
    sa.Column('goleador_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prediction', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('goleador_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('prediction',
    sa.Column('pred_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('team1', sa.String(length=3), nullable=True),
    sa.Column('team2', sa.String(length=3), nullable=True),
    sa.Column('goals1', sa.Integer(), nullable=True),
    sa.Column('goals2', sa.Integer(), nullable=True),
    sa.Column('winner', sa.Integer(), nullable=True),
    sa.Column('stage', sa.String(length=16), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('pred_id')
    )
    with op.batch_alter_table('prediction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prediction_game_id'), ['game_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prediction_game_id'))

    op.drop_table('prediction')
    op.drop_table('goleador')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_utc_time'))

    op.drop_table('game')
    # ### end Alembic commands ###
