"""empty message

Revision ID: e1d773b45d16
Revises: 
Create Date: 2022-11-11 15:18:45.892705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1d773b45d16'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('utc_time', sa.DateTime(), nullable=True),
    sa.Column('team1', sa.String(length=3), nullable=True),
    sa.Column('team2', sa.String(length=3), nullable=True),
    sa.Column('group', sa.String(length=1), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('stage', sa.String(length=16), nullable=True),
    sa.Column('cell1', sa.String(length=4), nullable=True),
    sa.Column('cell2', sa.String(length=4), nullable=True),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_index(op.f('ix_game_utc_time'), 'game', ['utc_time'], unique=False)
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('prediction',
    sa.Column('pred_id', sa.String(length=5), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('team1', sa.String(length=3), nullable=True),
    sa.Column('team2', sa.String(length=3), nullable=True),
    sa.Column('goals1', sa.Integer(), nullable=True),
    sa.Column('goals2', sa.Integer(), nullable=True),
    sa.Column('winner', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('pred_id')
    )
    op.create_index(op.f('ix_prediction_game_id'), 'prediction', ['game_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prediction_game_id'), table_name='prediction')
    op.drop_table('prediction')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_game_utc_time'), table_name='game')
    op.drop_table('game')
    # ### end Alembic commands ###
