"""empty message

Revision ID: ef00d958c52b
Revises: 8adb37392a67
Create Date: 2022-11-18 16:02:54.198017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef00d958c52b'
down_revision = '8adb37392a67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('official_goals1', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('official_goals2', sa.Integer(), nullable=True))
        batch_op.drop_column('goals1')
        batch_op.drop_column('goals2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goals2', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('goals1', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('official_goals2')
        batch_op.drop_column('official_goals1')

    # ### end Alembic commands ###
